---
- name: Deploy Nginx Proxy Manager using Docker Compose in nginxtest directory
  hosts: localhost
  become: yes

  vars:
    project_dir: "{{ ansible_user_dir }}/nginxtest"

  tasks:
    - name: Create nginxtest directory if it doesn't exist
      ansible.builtin.file:
        path: "{{ project_dir }}"
        state: directory
        mode: '0755'

    - name: Create docker-compose.yml file
      ansible.builtin.copy:
        dest: "{{ project_dir }}/docker-compose.yml"
        content: |
          services:
            app:
              image: 'jc21/nginx-proxy-manager:latest'
              restart: unless-stopped
              ports:
                - '80:80'
                - '81:81'
                - '443:443'
              volumes:
                - ./data:/data
                - ./letsencrypt:/etc/letsencrypt
        mode: '0644'

    - name: Run Docker Compose to start the service
      ansible.builtin.shell: docker compose up -d
      args:
        chdir: "{{ project_dir }}"
